### ISSUE TITLE
Illegal string offset 'contentType

### ISSUE THREAD

**Issue by xorgxx** [tomazahlin/symfony-mailer-bundle#3]
i have done this : 

```
parameters:
    _title          : test
    _homeUrl        : https://www.xorg.com
    _logoUrl        : https://www.xorg.com/img/logo.png
    _unsubscribeUrl : https://www.xorg.com/unsubscribe
    _infoEmail      : info@xorg.com



services:
    messager.sender:
        class: MessagerBundle\Controller\Services\Messager
        arguments:
            - @ahlin_mailer.mailing

    messager.template:
        class: MessagerBundle\Mapping\TemplateMapping
        public: false
        arguments:
            - %_title%
            - %_homeUrl%
            - %_logoUrl%
            - %_unsubscribeUrl%
            - %_infoEmail%
        tags:
            - { name: ahlin_mailer.mapping }
```

but i get this error 

```
Warning: Illegal string offset 'contentType' 

in vendor\tomazahlin\symfony-mailer-bundle\src\Ahlin\Mailer\Mailer.php at line 63  -

                $message = $this->renderer->render($mail);
                $this->swiftMailer->send($message);
            } catch(Exception $e) {
                throw new MailerException($e->getMessage(), $e->getCode());
            }
        }


```

here is my class : 

```
`    namespace MessagerBundle\Mapping;

    use Ahlin\Mailer\Mapping\TemplateMappingInterface;

    class TemplateMapping implements TemplateMappingInterface
    {
        public function getMappings()
        {
            return array(
                'xorg'              => array('view' => 'MessagerBundle:Mail:default.html.twig',             'contentType' => 'text/html'),
//                'registration'      => array('view' => 'CompanyUserBundle:Mail:registration.html.twig',     'contentType' => 'text/html'),
//                'activation'        => array('view' => 'CompanyUserBundle:Mail:activation.html.twig',       'contentType' => 'text/html'),
//                'forgot_password'   => array('view' => 'CompanyUserBundle:Mail:forgot_password.html.twig',  'contentType' => 'text/html'),
            );
        }

    }
```

can you help ?

**Comment by xorgxx** [comment]
i think the problem come from this code ligne 76 in namespace Ahlin\Mailer\Renderer  Renderer

```
        // Set default content type for each template, if not present
        foreach ($templates as $template) {
            if (!isset($template['contentType'])) {
                $template['contentType'] = $this->defaultContentType;
            }
        }
```

**Comment by xorgxx** [comment]
so solution one problem "My misteck" 

```
    messager.template:
        class: MessagerBundle\Mapping\TemplateMapping
        public: false
        arguments:
            - %_title%
            - %_homeUrl%
            - %_logoUrl%
            - %_unsubscribeUrl%
            - %_infoEmail%
        tags:
            - { name: ahlin_mailer.mapping }
```

by 

```
    messager.template:
        class: MessagerBundle\Mapping\TemplateMapping
        public: false
        arguments:
            - ahlin_mailer.default.parameters
        tags:
            - { name: ahlin_mailer.mapping }
```

now this is ok, but i style get `Warning: Illegal string offset 'contentType'`
